package actions

import (
	"net/http"

	_ "github.com/factly/data-portal-api/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/go-chi/chi"
	httpSwagger "github.com/swaggo/http-swagger"
)

// RegisterRoutes - CRUD servies
func RegisterRoutes() http.Handler {
	r := chi.NewRouter()

	r.Route("/currencies", func(r chi.Router) {
		r.Post("/", CreateCurrency)
		r.Route("/{id}", func(r chi.Router) {
			r.Get("/", GetCurrency)
			r.Delete("/", DeleteCurrency)
			r.Put("/", UpdateCurrency)
		})
	})
	r.Route("/users", func(r chi.Router) {
		r.Post("/", CreateUser)
		r.Route("/{id}", func(r chi.Router) {
			r.Get("/", GetUser)
			r.Delete("/", DeleteUser)
			r.Put("/", UpdateUser)
		})
	})
	r.Route("/plans", func(r chi.Router) {
		r.Post("/", CreatePlan)
		r.Route("/{id}", func(r chi.Router) {
			r.Get("/", GetPlan)
			r.Delete("/", DeletePlan)
			r.Put("/", UpdatePlan)
		})

	})
	r.Route("/memberships", func(r chi.Router) {
		r.Post("/", CreateMembership)
		r.Route("/{id}", func(r chi.Router) {
			r.Get("/", GetMembership)
			r.Delete("/", DeleteMembership)
			r.Put("/", UpdateMembership)
		})

	})
	r.Route("/payments", func(r chi.Router) {
		r.Post("/", CreatePayment)
		r.Route("/{id}", func(r chi.Router) {
			r.Get("/", GetPayment)
			r.Delete("/", DeletePayment)
			r.Put("/", UpdatePayment)
		})
	})
	r.Route("/products", func(r chi.Router) {
		r.Post("/", CreateProduct)
		r.Route("/{id}", func(r chi.Router) {
			r.Get("/", GetProduct)
			r.Delete("/", DeleteProduct)
			r.Put("/", UpdateProduct)
			r.Post("/type", CreateProductType)
			r.Post("/status", CreateStatus)
		})
	})
	r.Route("/tags", func(r chi.Router) {
		r.Post("/", CreateTag)
		r.Route("/{id}", func(r chi.Router) {
			r.Get("/", GetTag)
			r.Delete("/", DeleteTag)
			r.Put("/", UpdateTag)
		})

	})

	// swagger docs
	r.Get("/swagger/*", httpSwagger.WrapHandler)

	return r
}
